Task 1:
1. Train the Logistic Regression model and try without feature scaling and compare
accuracy on “Churn_Modelling” Dataset
2. Use Log Loss to find error
4. Use another dataset from Kaggle for classification and interpret result in your own
words
4. Change threshold manually (0.3, 0.7) and display results

Task 2: Study of Evaluation Metrics for Regression Models
1. Perform a detailed study of the following evaluation metrics:
a) Mean Absolute Error (MAE)
b) Mean Squared Error (MSE)
c) R2 Score (R2 Error)
2. For each metric, explain:
1) What the metric measures
2) How it evaluates the performance of a regression model
3) Its mathematical intuition (in simple words)

3. Analyze and discuss:
1) What range of values indicates good model performance?
2) What range of values indicates poor model performance?
3) How these metrics differ from each other in evaluating errors

4. Use the insurance Dataset attached in Lab 11, and Apply these metrics on any
sample regression model (using Python/Scikit-learn) and:
1) Compute MAE, MSE, and R2 Score
2) Interpret the results (in your own words) in terms of model accuracy and error

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix, classification_report

df = pd.read_csv("Churn_Modelling2.csv")

print(df.head())
print(df.shape)
print(df.info())
print(df.describe())

X = df.drop(columns=["RowNumber", "CustomerId", "Surname", "Exited"])
y = df["Exited"]

X = pd.get_dummies(X, columns=["Gender"], drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model_without_scaling = LogisticRegression(max_iter=5000) # Increased max_iter
model_without_scaling.fit(X_train, y_train)

y_pred_without_scaling = model_without_scaling.predict(X_test)
y_prob_without_scaling = model_without_scaling.predict_proba(X_test)[:, 1]

accuracy_without_scaling = accuracy_score(y_test, y_pred_without_scaling)
logloss_without_scaling = log_loss(y_test, y_prob_without_scaling)

print("Without Feature Scaling")
print("Accuracy:", accuracy_without_scaling)
print("Log Loss:", logloss_without_scaling)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_without_scaling))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_without_scaling))

   RowNumber  CustomerId   Surname  CreditScore  Gender  Age  Tenure  \
0          1    15634602  Hargrave          619  Female   42       2   
1          2    15647311      Hill          608  Female   41       1   
2          3    15619304      Onio          502  Female   42       8   
3          4    15701354      Boni          699  Female   39       1   
4          5    15737888  Mitchell          850  Female   43       2   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              1          1               1        101348.88   
1   83807.86              1          0               1        112542.58   
2  159660.80              3          1               0        113931.57   
3       0.00              2          0               0         93826.63   
4  125510.82              1          1               1         79084.10   

   Exited  
0       1  
1       0  
2       1  
3       0  
4       0  
(10000, 13)
<class 'pandas.core.frame.DataFr

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model_scaled = LogisticRegression(max_iter=1000)
model_scaled.fit(X_train_scaled, y_train)

y_pred_scaled = model_scaled.predict(X_test_scaled)
y_prob_scaled = model_scaled.predict_proba(X_test_scaled)[:, 1]

accuracy_scaled = accuracy_score(y_test, y_pred_scaled)
logloss_scaled = log_loss(y_test, y_prob_scaled)

print("With Feature Scaling")
print("Accuracy:", accuracy_scaled)
print("Log Loss:", logloss_scaled)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_scaled))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_scaled))

With Feature Scaling
Accuracy: 0.805
Log Loss: 0.4279149352836577

Confusion Matrix:
[[1550   43]
 [ 347   60]]

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.97      0.89      1593
           1       0.58      0.15      0.24       407

    accuracy                           0.81      2000
   macro avg       0.70      0.56      0.56      2000
weighted avg       0.77      0.81      0.76      2000



In [6]:
comparison = pd.DataFrame({
    "Model": ["Without Scaling", "With Scaling"],
    "Accuracy": [accuracy_without_scaling, accuracy_scaled],
    "Log Loss": [logloss_without_scaling, logloss_scaled]
})

print(comparison)

             Model  Accuracy  Log Loss
0  Without Scaling    0.8105  0.429183
1     With Scaling    0.8050  0.427915


In [7]:
print("Log Loss Without Scaling:", logloss_without_scaling)
print("Log Loss With Scaling:", logloss_scaled)

Log Loss Without Scaling: 0.4291827103769062
Log Loss With Scaling: 0.4279149352836577


In [8]:
thresholds = [0.3, 0.5, 0.7]

for threshold in thresholds:
    y_pred_threshold = (y_prob_scaled >= threshold).astype(int)

    accuracy = accuracy_score(y_test, y_pred_threshold)

    print("\nThreshold:", threshold)
    print("Accuracy:", accuracy)
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred_threshold))
    print("Classification Report:")
    print(classification_report(y_test, y_pred_threshold))


Threshold: 0.3
Accuracy: 0.7755
Confusion Matrix:
[[1355  238]
 [ 211  196]]
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.85      0.86      1593
           1       0.45      0.48      0.47       407

    accuracy                           0.78      2000
   macro avg       0.66      0.67      0.66      2000
weighted avg       0.78      0.78      0.78      2000


Threshold: 0.5
Accuracy: 0.805
Confusion Matrix:
[[1550   43]
 [ 347   60]]
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.97      0.89      1593
           1       0.58      0.15      0.24       407

    accuracy                           0.81      2000
   macro avg       0.70      0.56      0.56      2000
weighted avg       0.77      0.81      0.76      2000


Threshold: 0.7
Accuracy: 0.7985
Confusion Matrix:
[[1589    4]
 [ 399    8]]
Classification Report:
              precision    recall  f1-score 