Name: Adil Khan
----
Roll no: 2330-0030
----
Department: BS AI

In [2]:
import numpy as np


1. Create a 1D array of 20 random integers between 1 and 100.

In [3]:
arr1 = np.random.randint(1, 101, 20)
print(arr1)


[34  3 97 40 68 91 66 51 72  1 34 90 18 49 49 62 39 76 32 20]


2. Reshape the above array into a 4x5 matrix.

In [17]:
matrix = arr1.reshape(4, 5)
print(matrix)


[[34  3 97 40 68]
 [91 66 51 72  1]
 [34 90 18 49 49]
 [62 39 76 32 20]]


3. Extract the diagonal elements of a 4x4 identity matrix.

In [18]:
diag_values = np.diag(np.eye(4))
print(diag_values)


[1. 1. 1. 1.]


4. Create a 2D array of shape (5, 5) with random integers between 0 and 9, and replace all even
values with -1.

In [6]:
arr2 = np.random.randint(0, 10, (5, 5))
arr2[arr2 % 2 == 0] = -1
print(arr2)


[[ 9  1  3  5  3]
 [ 7  7 -1 -1  1]
 [-1 -1 -1 -1 -1]
 [ 9 -1 -1  5 -1]
 [ 3 -1  9  9  7]]


5. Given two arrays a and b, find the common elements between them.

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([4, 5, 6, 7, 8])

common = np.intersect1d(a, b)
print(common)


[4 5 6]


6. Calculate the matrix product of a 3x4 matrix and a 4x2 matrix.

In [16]:
A = np.random.randint(1, 10, (3, 4))
B = np.random.randint(1, 10, (4, 2))
print(A)
print(B)
product = np.dot(A, B)
print(product)


[[6 9 2 1]
 [7 4 5 7]
 [6 9 5 6]]
[[6 3]
 [1 3]
 [4 5]
 [6 3]]
[[ 59  58]
 [108  79]
 [101  88]]


7. Create a 1D array of 500 random values between 0 and 1.

In [9]:
arr3 = np.random.rand(500)
print(arr3)


[0.81459349 0.84113695 0.93701257 0.4963555  0.80739936 0.14228517
 0.60373663 0.22326486 0.21785105 0.82953798 0.18437213 0.27077351
 0.68721331 0.21237514 0.93259353 0.74973393 0.45515301 0.97592669
 0.58874948 0.86644528 0.77271791 0.46542464 0.43672778 0.96113016
 0.99493483 0.23688881 0.10200489 0.05652964 0.00803137 0.59129243
 0.82897131 0.20261707 0.65772297 0.76766242 0.38061091 0.51339123
 0.33489902 0.85957223 0.48579998 0.65359558 0.99337144 0.45864989
 0.09973198 0.62674151 0.13949713 0.94613527 0.43873088 0.55074495
 0.87867225 0.43137352 0.17603619 0.06342378 0.10859864 0.60328497
 0.71201227 0.07679691 0.61472003 0.82463555 0.90917414 0.15793285
 0.54385681 0.51482802 0.34577871 0.65959252 0.82544293 0.53359545
 0.27426573 0.3426489  0.05138336 0.92637926 0.24385992 0.44580785
 0.76549589 0.74232814 0.63837489 0.0981156  0.76247542 0.6481452
 0.70772077 0.36317852 0.2239335  0.10471383 0.1338781  0.10564067
 0.81061703 0.66480437 0.03377758 0.61257123 0.53259544 0.03766

8. Generate a 10x10 identity matrix.

In [14]:
Lan = np.eye(10)
print(Lan)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


9. Use numpy to shuffle the rows randomly in above task.

In [19]:
shuffled_L = Lan.copy()
np.random.shuffle(shuffled_L)
print(shuffled_L)


[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


10. Generate an array of 10 random integers between 50 and 150 using Numpy. Find the minimum,
maximum, and the sum of the elements in the array.

In [12]:
arr4 = np.random.randint(50, 151, 10)

min_val = arr4.min()
max_val = arr4.max()
sum_val = arr4.sum()

print("Array:", arr4)
print("Min:", min_val)
print("Max:", max_val)
print("Sum:", sum_val)


Array: [149  94  51 146 135  55 126 141 124  93]
Min: 51
Max: 149
Sum: 1114
