Name: Adil Khan     
Roll No: 2330-0030    


Take user input for a start value, a stop value and a "size" value. Generate a diagonal matrix of
the given size based on these that starts from the given number and populates the diagonal of
the matrix with numbers from start to stop value having equal distance between every two
numbers in the diagonal.

In [2]:
import numpy as np

start = float(input("Enter start value: "))
stop = float(input("Enter stop value: "))
size = int(input("Enter matrix size: "))

diagonal_values = np.linspace(start, stop, size)
diagonal_matrix = np.diag(diagonal_values)

print("Diagonal Matrix:")
print(diagonal_matrix)


Enter start value: 2
Enter stop value: 10
Enter matrix size: 5
Diagonal Matrix:
[[ 2.  0.  0.  0.  0.]
 [ 0.  4.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.]
 [ 0.  0.  0.  8.  0.]
 [ 0.  0.  0.  0. 10.]]


Make a simple restaurant billing system that provides a menu of any 10 different dishes. These
dishes will be displayed to the user in a random order. The user can order as many dishes as
they want and their price will be stored individually in an array. Take such orders from at least
2 different customers then print out the final bill for each customer. Also print the maximum
bill, minimun bill, the mean and the median. Additionally, keep track of the total restaurant
earnings by finding out the cummulative sum of the bills.

In [3]:
import random
import statistics

menu = {
    "Burger": 250,
    "Pizza": 800,
    "Pasta": 600,
    "Sandwich": 200,
    "Fries": 150,
    "Biryani": 350,
    "Karahi": 1200,
    "BBQ": 900,
    "Ice Cream": 180,
    "Cold Drink": 120
}

customers_bills = []
num_customers = 2

for c in range(num_customers):
    print(f"\nCustomer {c+1}")

    items = list(menu.items())
    random.shuffle(items)

    for i, (dish, price) in enumerate(items, start=1):
        print(f"{i}. {dish} - Rs {price}")

    prices = []

    while True:
        choice = int(input("Enter dish number (0 to finish): "))
        if choice == 0:
            break
        prices.append(items[choice-1][1])

    bill = sum(prices)
    customers_bills.append(bill)
    print(f"Total Bill for Customer {c+1}: Rs {bill}")

max_bill = max(customers_bills)
min_bill = min(customers_bills)
mean_bill = statistics.mean(customers_bills)
median_bill = statistics.median(customers_bills)
total_earnings = sum(customers_bills)

print("\nBills:", customers_bills)
print("Maximum Bill:", max_bill)
print("Minimum Bill:", min_bill)
print("Mean Bill:", mean_bill)
print("Median Bill:", median_bill)
print("Total Restaurant Earnings:", total_earnings)



Customer 1
1. Cold Drink - Rs 120
2. BBQ - Rs 900
3. Pizza - Rs 800
4. Burger - Rs 250
5. Biryani - Rs 350
6. Fries - Rs 150
7. Ice Cream - Rs 180
8. Sandwich - Rs 200
9. Karahi - Rs 1200
10. Pasta - Rs 600
Enter dish number (0 to finish): 7
Enter dish number (0 to finish): 2
Enter dish number (0 to finish): 3
Enter dish number (0 to finish): 0
Total Bill for Customer 1: Rs 1880

Customer 2
1. Burger - Rs 250
2. Cold Drink - Rs 120
3. BBQ - Rs 900
4. Pasta - Rs 600
5. Biryani - Rs 350
6. Ice Cream - Rs 180
7. Pizza - Rs 800
8. Fries - Rs 150
9. Sandwich - Rs 200
10. Karahi - Rs 1200
Enter dish number (0 to finish): 10
Enter dish number (0 to finish): 9
Enter dish number (0 to finish): 8
Enter dish number (0 to finish): 7
Enter dish number (0 to finish): 0
Total Bill for Customer 2: Rs 2350

Bills: [1880, 2350]
Maximum Bill: 2350
Minimum Bill: 1880
Mean Bill: 2115
Median Bill: 2115.0
Total Restaurant Earnings: 4230


Let the user input random characters to populate two 4x4 matrices. Find out the largest
character (character with the highest integer value) in both and print that. Further perform
matrix multiplication on the two matrices to form a third Matrix. Display it as a matrix of
characters. (Note: You can use the ord() function to convert the character to integer.)

In [4]:
import numpy as np

A = []
B = []

print("Enter characters for Matrix A (4x4):")
for i in range(4):
    row = []
    for j in range(4):
        row.append(input())
    A.append(row)

print("Enter characters for Matrix B (4x4):")
for i in range(4):
    row = []
    for j in range(4):
        row.append(input())
    B.append(row)

A = np.array(A)
B = np.array(B)

max_char_A = max(A.flatten(), key=lambda x: ord(x))
max_char_B = max(B.flatten(), key=lambda x: ord(x))

print("Largest character in Matrix A:", max_char_A)
print("Largest character in Matrix B:", max_char_B)

A_int = np.vectorize(ord)(A)
B_int = np.vectorize(ord)(B)

C_int = np.matmul(A_int, B_int)

C_char = np.vectorize(lambda x: chr(x % 128))(C_int)

print("Resultant Matrix:")
print(C_char)


Enter characters for Matrix A (4x4):
z
y
a
f
g
h
i
l
x
j
m
n
o
p
q
r
Enter characters for Matrix B (4x4):
a
s
d
f
y
u
i
o
w
q
b
n
m
k
c
w
Largest character in Matrix A: z
Largest character in Matrix B: y
Resultant Matrix:
[['p' '\x0e' ']' '+']
 ['z' 'J' 'Z' 't']
 ['\x13' 'q' '\x1e' '>']
 ['\x10' '\x14' '$' 'V']]


Choose any problem whose implementation will require usage of at least 3 of the different numpy
concepts we have studied (e.g. Taking the dot product of two matrices, stacking all three matrices
on top of each other then broadcasting the resulting matrix against a scalar). Save the resulting
solutions into files.

In [5]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[2, 2, 2],
              [3, 3, 3],
              [4, 4, 4]])

dot_product = np.dot(A, B)

stacked_matrix = np.vstack((A, B, C))

broadcasted_matrix = stacked_matrix * 2

np.savetxt("matrix_A.txt", A, fmt="%d")
np.savetxt("matrix_B.txt", B, fmt="%d")
np.savetxt("matrix_C.txt", C, fmt="%d")
np.savetxt("dot_product.txt", dot_product, fmt="%d")
np.savetxt("stacked_matrix.txt", stacked_matrix, fmt="%d")
np.savetxt("broadcasted_matrix.txt", broadcasted_matrix, fmt="%d")

print("All matrices and results have been saved to files.")


All matrices and results have been saved to files.


You are required to create an Employee Management System by defining classes and using the
concept of inheritance, polymorphism, abstraction, and encapsulation where needed. Each
employee should have the following attributes:
• Employee_id
• Name
• Department
• Salary
• Email
• Skills (list of string, e.g.,[“python”, “excel”])
• Address (tuple, e.g., (“Islamabad”, “Karachi”))
Task:
Write a Python program that:
1. Initializes a dictionary to store details of at least five employees, where each employee's
details are stored as a nested dictionary.
2. Provides a function to add a new employee to the dictionary. (input from user)
3. Includes a function to update an employee’s salary and skills based on their
employee_id.
4. Includes a function to delete an employee's record
5. Write a function to retrieve and display all employees in a specified department (e.g.,
"IT").
6. Handles errors, such as attempting to update a non-existent employee.
7. Displays a summary report showing:
• Total employees
• Departments available
• Average salary per department

In [7]:
from abc import ABC, abstractmethod

class Employee(ABC):
    def __init__(self, employee_id, name, department, salary, email, skills, address):
        self.__employee_id = employee_id
        self.__name = name
        self.__department = department
        self.__salary = salary
        self.__email = email
        self.__skills = skills
        self.__address = address

    def get_id(self):
        return self.__employee_id

    def get_department(self):
        return self.__department

    def get_salary(self):
        return self.__salary

    def set_salary(self, salary):
        if salary > 0:
            self.__salary = salary

    def set_skills(self, skills):
        self.__skills = skills

    def to_dict(self):
        return {
            "Employee_id": self.__employee_id,
            "Name": self.__name,
            "Department": self.__department,
            "Salary": self.__salary,
            "Email": self.__email,
            "Skills": self.__skills,
            "Address": self.__address
        }

    @abstractmethod
    def role(self):
        pass


class Staff(Employee):
    def role(self):
        return "Staff"


employees = {
    101: Staff(101, "Ali", "IT", 120000, "ali@company.com", ["python", "excel"], ("Islamabad", "Karachi")).to_dict(),
    102: Staff(102, "Sara", "HR", 90000, "sara@company.com", ["recruitment"], ("Lahore", "Islamabad")).to_dict(),
    103: Staff(103, "Ahmed", "IT", 110000, "ahmed@company.com", ["java"], ("Karachi", "Lahore")).to_dict(),
    104: Staff(104, "Zain", "Finance", 100000, "zain@company.com", ["accounting"], ("Islamabad", "Lahore")).to_dict(),
    105: Staff(105, "Ayesha", "IT", 130000, "ayesha@company.com", ["python", "sql"], ("Lahore", "Karachi")).to_dict()
}


def add_employee():
    try:
        emp_id = int(input("Enter Employee ID: "))
        if emp_id in employees:
            print("Employee already exists")
            return

        name = input("Enter Name: ")
        dept = input("Enter Department: ")
        salary = float(input("Enter Salary: "))
        email = input("Enter Email: ")
        skills = input("Enter Skills (comma separated): ").split(",")
        city1 = input("Enter City 1: ")
        city2 = input("Enter City 2: ")

        emp = Staff(emp_id, name, dept, salary, email, skills, (city1, city2))
        employees[emp_id] = emp.to_dict()
        print("Employee added successfully")

    except ValueError:
        print("Invalid input")


def update_employee(emp_id):
    if emp_id not in employees:
        print("Employee not found")
        return

    salary = float(input("Enter new salary: "))
    skills = input("Enter new skills (comma separated): ").split(",")

    employees[emp_id]["Salary"] = salary
    employees[emp_id]["Skills"] = skills
    print("Employee updated successfully")


def delete_employee(emp_id):
    if emp_id not in employees:
        print("Employee not found")
        return

    del employees[emp_id]
    print("Employee deleted successfully")


def display_by_department(department):
    found = False
    for emp in employees.values():
        if emp["Department"] == department:
            print(emp)
            found = True
    if not found:
        print("No employees in this department")


def summary_report():
    print("Total Employees:", len(employees))

    departments = set()
    dept_salary = {}
    dept_count = {}

    for emp in employees.values():
        dept = emp["Department"]
        salary = emp["Salary"]

        departments.add(dept)
        dept_salary[dept] = dept_salary.get(dept, 0) + salary
        dept_count[dept] = dept_count.get(dept, 0) + 1

    print("Departments Available:", departments)

    for dept in dept_salary:
        avg_salary = dept_salary[dept] / dept_count[dept]
        print(f"Average Salary in {dept}: {avg_salary}")


# Example Usage
add_employee()
update_employee(101)
delete_employee(102)
display_by_department("IT")
summary_report()


Enter Employee ID: 101
Employee already exists
Enter new salary: 104
Enter new skills (comma separated): IT
Employee updated successfully
Employee deleted successfully
{'Employee_id': 101, 'Name': 'Ali', 'Department': 'IT', 'Salary': 104.0, 'Email': 'ali@company.com', 'Skills': ['IT'], 'Address': ('Islamabad', 'Karachi')}
{'Employee_id': 103, 'Name': 'Ahmed', 'Department': 'IT', 'Salary': 110000, 'Email': 'ahmed@company.com', 'Skills': ['java'], 'Address': ('Karachi', 'Lahore')}
{'Employee_id': 105, 'Name': 'Ayesha', 'Department': 'IT', 'Salary': 130000, 'Email': 'ayesha@company.com', 'Skills': ['python', 'sql'], 'Address': ('Lahore', 'Karachi')}
Total Employees: 4
Departments Available: {'Finance', 'IT'}
Average Salary in IT: 80034.66666666667
Average Salary in Finance: 100000.0
